language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: cd tests; python -m nose
after_success:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: pypi
  user: rkuykendall
  password:
    secure: edT/+BPxj8LCs7XcB2FOuTvdHWmFVbRMU7a3HYqVOXB6ZX6va4bfNPze2BxiDbZK2BvY8gDTD6xX8t2SZNBdBv7EurQ8wKTbFGGn8+wRUYw9hrhGdTkbpmxJ9O1YY14q5jQrfqEcTdpTZAe9k0D9X/Qv4ApL9XSge7K9caReHJlZ7/jCz3DxP7uop5Jf0SV++o3tLWQTyqimY5xorPtUgqiviJTJD5qjR59DxmbrjLAH747MKna9n5ZAgQ+gtN9YfhZWOq26s8aVAhsnDCrlQxfFKxckTCo7+d++UEFmVdZkCg3nq4Pr/IsaI5yBGMQSz6Zbk9DVlCPTUx7vEU9s8qs6mbemvhMXL6iN57YTvxiiA+n03NrS/I6Ldi2Znl1R/i9o0hDjpTEO+3SD9LrYkZfOlCXGdNOFnPGsAOT3ojR4KwEni9atmeisqIS5WoGHAB54ga+zA0W9OxM1dO9v9cVUGLD+WyrFmRfsVVxIoXlmBM7XwazsCmEY6U4DXOllqH7wcFV0hleR+XCy8/g8qeuRZNUve0b1iNLsPP6G6iR91S6w0bG8Kl8oLOmD6yhDXqmpX4GIsa8PAVLVTfiEiFfKHy8bXU35ITsKa0E3SR5gFpKtd70/86qr/NRUZwMq8d39yAqZKd0SBKjPQzcKVyZ5gj7aRDR6q3Be80OwimI=
  on:
    tags: true
    repo: rkuykendall/marvelous
